#!/bin/bash
# Startup script for Databricks Apps

# Ensure HOME is set — Databricks Apps may leave it empty
if [ -z "$HOME" ] || [ "$HOME" = "/" ]; then
    export HOME="/home/$(whoami)"
    mkdir -p "$HOME" 2>/dev/null || export HOME="/tmp/app-home"
    mkdir -p "$HOME"
fi

export PATH="$HOME/.local/bin:$PATH"
export ANTIWORD_DATA="$HOME/.antiword"

# ── antiword (.doc → text) ────────────────────────────────────────────────────
if ! command -v antiword &>/dev/null; then
    ARCH=$(uname -m)
    T=$(mktemp -d)
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

    # 1. Use bundled .deb if present (fastest, no network) — vendored under data/vendor/antiword/
    if ls "$SCRIPT_DIR"/data/vendor/antiword/antiword*.deb &>/dev/null; then
        cp "$SCRIPT_DIR"/data/vendor/antiword/antiword*.deb "$T/antiword.deb"
    fi

    # 2. Try apt-get download (no root, uses pre-populated apt cache)
    if ! ls "$T"/antiword*.deb &>/dev/null; then
        (cd "$T" && apt-get download antiword 2>/dev/null)
    fi

    # 3. Fall back to direct .deb download if needed
    if ! ls "$T"/antiword*.deb &>/dev/null; then
        [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "amd64" ] && URLS=(
            "http://archive.ubuntu.com/ubuntu/pool/universe/a/antiword/antiword_0.37-16_amd64.deb"
            "http://archive.ubuntu.com/ubuntu/pool/universe/a/antiword/antiword_0.37-15build1_amd64.deb"
            "https://deb.debian.org/debian/pool/main/a/antiword/antiword_0.37-15+b1_amd64.deb"
        )
        [ "$ARCH" = "aarch64" ] && URLS=(
            "http://ports.ubuntu.com/ubuntu-ports/pool/universe/a/antiword/antiword_0.37-16_arm64.deb"
            "http://ports.ubuntu.com/ubuntu-ports/pool/universe/a/antiword/antiword_0.37-15build1_arm64.deb"
        )
        for URL in "${URLS[@]:-}"; do
            curl -fsSL --max-time 20 "$URL" -o "$T/antiword.deb" 2>/dev/null && break
            rm -f "$T/antiword.deb"
        done
    fi

    DEB=$(ls "$T"/antiword*.deb 2>/dev/null | head -1)
    if [ -n "$DEB" ]; then
        dpkg -x "$DEB" "$T/pkg" 2>/dev/null
        mkdir -p "$HOME/.local/bin"
        cp "$T/pkg/usr/bin/antiword" "$HOME/.local/bin/antiword" && chmod +x "$HOME/.local/bin/antiword"
        mkdir -p "$ANTIWORD_DATA"
        cp "$T/pkg/usr/share/antiword/"* "$ANTIWORD_DATA/" 2>/dev/null || true
    fi
    rm -rf "$T"
fi

command -v antiword &>/dev/null \
    && echo "[startup] antiword ready" \
    || echo "[startup] antiword unavailable — .doc uses Python fallback"

# Per-environment overrides (COMPARE_VOLUME_PATH, CHAT_VSI_INDEX, …) generated by
# deploy_qualibot.ps1 and uploaded alongside the source files. Absent in local
# dev and in the Git Folder — app.yaml defaults apply in that case.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/target_config.env" ]; then
    # shellcheck source=/dev/null
    source "$SCRIPT_DIR/target_config.env"
fi

export TZ='Europe/Paris'

exec uvicorn server.app:app "$@"
